# Generated by Django 4.1.4 on 2022-12-12 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_lname', models.CharField(max_length=200)),
                ('cust_fname', models.CharField(max_length=200)),
                ('cust_email', models.EmailField(max_length=200)),
                ('cust_address', models.TextField()),
                ('cust_image', models.CharField(max_length=200)),
                ('cust_phone', models.CharField(max_length=20)),
                ('date_joined', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('stock_no', models.IntegerField()),
                ('manufacturer_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('product_price', models.FloatField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_refno', models.CharField(max_length=200)),
                ('trx_status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('paid', 'Paid')], max_length=50)),
                ('trx_method', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash')], max_length=50)),
                ('trx_paygate', models.TextField()),
                ('trx_date', models.DateTimeField(auto_now=True)),
                ('trx_expiry', models.DateTimeField()),
                ('trx_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_trx', to='ecomtech.customer')),
                ('trx_totalamt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_trx', to='ecomtech.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now=True)),
                ('cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartdeets', to='ecomtech.customer')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_cart', to='ecomtech.product')),
            ],
        ),
    ]
