# Generated by Django 4.1.4 on 2022-12-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomtech', '0002_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_fname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_lname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trx_expiry',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trx_method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trx_paygate',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trx_refno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trx_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('paid', 'Paid')], max_length=50, null=True),
        ),
    ]
