# Generated by Django 4.1.4 on 2023-03-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomtech', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cust_password',
        ),
    ]
