# Generated by Django 4.1.4 on 2022-12-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomtech', '0004_cart_quantity_added_product_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_image',
            field=models.ImageField(max_length=200, null=True, upload_to='customers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(max_length=200, null=True, upload_to='products/'),
        ),
    ]
