# Generated by Django 4.1.4 on 2022-12-30 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomtech', '0005_alter_customer_cust_image_alter_product_prod_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Acessories', 'Accessories'), ('Phones', 'Phones'), ('Tablet', 'Tablet'), ('Camera', 'Cameras')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_name',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Amazon', 'Amazon'), ('Sony', 'Sony'), ('Dell', 'Dell'), ('HP', 'Hp'), ('Nokia', 'Nokia')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now=True)),
                ('cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishdeets', to='ecomtech.customer')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_wish', to='ecomtech.product')),
            ],
        ),
    ]
