# Generated by Django 4.1.4 on 2023-03-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomtech', '0006_remove_cart_products_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amt',
            field=models.FloatField(null=True),
        ),
    ]
