# Generated by Django 4.1.4 on 2023-05-06 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomtech', '0007_cart_total_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkoutdeets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
