# Generated by Django 4.1.4 on 2023-05-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomtech', '0008_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trx_totalamt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
