# Generated by Django 4.1.4 on 2024-06-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomtech', '0011_productcategory_productmanufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='trx_expiry',
        ),
        migrations.AddField(
            model_name='product',
            name='added_to_wishlist',
            field=models.BooleanField(null=True),
        ),
    ]
